"""
Training script for the ranking model.
"""
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from ml.recommendation.ranking.model import RankingModel

class RankingDataset(Dataset):
    def __init__(self, user_features_df, product_features_df, interactions_df, num_negatives=4):
        """
        user_features_df: DataFrame with user_id as index and user feature columns
        product_features_df: DataFrame with product_id as index and product feature columns
        interactions_df: DataFrame with columns ['user_id', 'product_id'] for positive interactions
        """
        self.user_features_df = user_features_df
        self.product_features_df = product_features_df
        self.interactions_df = interactions_df

        # Map user_id and product_id to indices for faster lookup
        self.user_id_to_index = {uid: idx for idx, uid in enumerate(user_features_df.index)}
        self.product_id_to_index = {pid: idx for idx, pid in enumerate(product_features_df.index)}

        self.all_product_ids = set(product_features_df.index)

        # Prepare positive samples
        self.pos_samples = []
        for _, row in interactions_df.iterrows():
            uid = row['user_id']
            pid = row['product_id']
            if uid in self.user_id_to_index and pid in self.product_id_to_index:
                self.pos_samples.append((uid, pid, 1))  # label 1 for positive

        # Prepare negative samples
        self.neg_samples = []
        for _, row in interactions_df.iterrows():
            uid = row['user_id']
            # Sample negative products for this user
            user_interacted_products = set(interactions_df[interactions_df['user_id'] == uid]['product_id'])
            negative_candidates = list(self.all_product_ids - user_interacted_products)
            if len(negative_candidates) > 0:
                sampled_negatives = np.random.choice(
                    negative_candidates,
                    size=min(num_negatives, len(negative_candidates)),
                    replace=False
                )
                for pid in sampled_negatives:
                    if uid in self.user_id_to_index and pid in self.product_id_to_index:
                        self.neg_samples.append((uid, pid, 0))  # label 0 for negative

        self.samples = self.pos_samples + self.neg_samples
        np.random.shuffle(self.samples)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        uid, pid, label = self.samples[idx]
        user_idx = self.user_id_to_index[uid]
        product_idx = self.product_id_to_index[pid]

        user_features = torch.FloatTensor(self.user_features_df.iloc[user_idx].values)
        product_features = torch.FloatTensor(self.product_features_df.iloc[product_idx].values)
        label = torch.FloatTensor([label])

        return user_features, product_features, label

def main():
    # Load features (we'll read from the Parquet files generated by the Spark jobs)
    user_features_df = pd.read_parquet('./data_lake/user_features/')
    product_features_df = pd.read_parquet('./data_lake/product_features/')

    # Set index to user_id and product_id
    user_features_df.set_index('user_id', inplace=True)
    product_features_df.set_index('product_id', inplace=True)

    # Load interactions (from events)
    # For simplicity, we'll read from the event consumer's output (the data lake events)
    # We'll read all events and aggregate interactions per user-product
    events_df = pd.read_json('./data_lake/*/*', lines=True)
    # Consider an interaction if there's at least one event (view, click, purchase)
    interactions_df = events_df[['user_id', 'product_id']].drop_duplicates()

    # Create dataset
    dataset = RankingDataset(user_features_df, product_features_df, interactions_df, num_negatives=4)
    dataloader = DataLoader(dataset, batch_size=256, shuffle=True)

    user_feature_dim = user_features_df.shape[1]
    product_feature_dim = product_features_df.shape[1]

    model = RankingModel(user_feature_dim, product_feature_dim, hidden_dim=128)
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    num_epochs = 10
    for epoch in range(num_epochs):
        total_loss = 0
        for batch_user_features, batch_product_features, batch_labels in dataloader:
            optimizer.zero_grad()
            outputs = model(batch_user_features, batch_product_features)
            loss = criterion(outputs, batch_labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {total_loss/len(dataloader):.4f}')

    # Save the model
    torch.save(model.state_dict(), './models/ranking_model.pth')

if __name__ == '__main__':
    main()