apiVersion: v1
kind: Service
metadata:
  name: recommendation-frontend
  namespace: recommendation-platform
  labels:
    app: recommendation-frontend
spec:
  selector:
    app: recommendation-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer