apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recommendation-platform.fullname" . }}-config
  labels:
    {{- include "recommendation-platform.labels" . | nindent 4 }}
{{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}