apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recommendation-platform.fullname" . }}-frontend
  labels:
    {{- include "recommendation-platform.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "recommendation-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recommendation-platform.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "recommendation-platform.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "recommendation-platform.fullname" . }}-config
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}