apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recommendation-platform.fullname" . }}-secrets
  labels:
    {{- include "recommendation-platform.labels" . | nindent 4 }}
{{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ $value | b64enc }}"
  {{- end }}